CREATE DATABASE LibraryDB;
GO
USE LibraryDB;
GO
CREATE TABLE Users (id INT IDENTITY PRIMARY KEY, username NVARCHAR(50) UNIQUE NOT NULL, hash NVARCHAR(200) NOT NULL, role NVARCHAR(10) NOT NULL CHECK (role IN ('admin','staff')));
CREATE TABLE Patrons (id INT IDENTITY PRIMARY KEY, code NVARCHAR(20) UNIQUE NOT NULL, name NVARCHAR(100) NOT NULL, contact NVARCHAR(100), active BIT NOT NULL DEFAULT 1);
CREATE TABLE Books (id INT IDENTITY PRIMARY KEY, title NVARCHAR(200) NOT NULL, author NVARCHAR(100) NOT NULL, genre NVARCHAR(50) NOT NULL, classification NVARCHAR(50));
CREATE TABLE BookCopies (id INT IDENTITY PRIMARY KEY, copyCode NVARCHAR(20) UNIQUE NOT NULL, bookId INT NOT NULL REFERENCES Books(id), status NVARCHAR(10) NOT NULL DEFAULT 'Available' CHECK (status IN ('Available','Borrowed')));
CREATE TABLE Loans (id INT IDENTITY PRIMARY KEY, patronId INT NOT NULL REFERENCES Patrons(id), copyId INT NOT NULL REFERENCES BookCopies(id), checkoutAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(), dueAt DATETIME2 NOT NULL, returnAt DATETIME2 NULL);
CREATE INDEX IX_Loans_patron ON Loans(patronId); CREATE INDEX IX_Loans_copy ON Loans(copyId);
CREATE TABLE Logs (id INT IDENTITY PRIMARY KEY, at DATETIME2 NOT NULL DEFAULT SYSDATETIME(), action NVARCHAR(50) NOT NULL, detail NVARCHAR(400), ms INT);
